DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS accounts;

-- 创建账户表
CREATE TABLE accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(80) NOT NULL,
    status ENUM('CREATED', 'ACTIVATED', 'DEACTIVATED') NOT NULL DEFAULT 'CREATED',
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建卡表
CREATE TABLE cards (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(50) NOT NULL,
    visible_number VARCHAR(20) NOT NULL,
    contract_id VARCHAR(20) NOT NULL,
    status ENUM('CREATED', 'ASSIGNED', 'ACTIVATED', 'DEACTIVATED') NOT NULL DEFAULT 'CREATED',
    account_id BIGINT,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;