spring:
  application:
    name: emsp-account-card-service
  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
  datasource:
    url: jdbc:mysql://localhost:3306/emsp_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/**/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true

logging:
  level:
    root: INFO
    com.emsp: DEBUG